Sprint-3/step-1
IgorKilipenko/react-burger pull request #4
Opened 2023-05-08 09:25 UTC by IgorKilipenko

Sprint-3/Step-1 for review

2023-05-08 09:57 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Хорошее знание `typescript`
- хорошая организация хранилища для работы с юзером

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Если не авторизованный юзер переходит на страницу профиля - это вызывает ошибку

<img width="909" alt="Снимок экрана 2023-05-08 в 12 49 42" src="https://user-images.githubusercontent.com/60173362/236793273-834aa4f6-8ed2-4043-9f40-421fab95784e.png">

- Вам нужно использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу. Вам должны были дать ссылку на документацию по этой логике. Вот она https://github.com/remix-run/react-router/blob/dev/examples/modal/src/App.tsx . Пожалуйста, посоветуйтесь с наставником.

- Не авторизованный юзер не должен иметь возможность сделать заказ
- Невозможно попасть на роуты логина, регистраци и восстановления пароля.
После восстановления доступа к этим страницам - пожалуйста убедитесь их корректной работе.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-08 09:57 UTC, andryxxa93 commented on src/components/app-router/routes.tsx
> +    path: "/register",
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-05-10 18:09 UTC, IgorKilipenko commented
Андрей, добрый день! по поводу пункта замечаний: `использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу` не могу пока разобраться как использовать указанный пример для `createBrowserRouter` как-бы формально то у меня механизм роутинга для попапа используется но не так как в задании.

2023-05-11 07:05 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-11 07:06 UTC, andryxxa93 commented
> Андрей, добрый день! по поводу пункта замечаний: `использовать средства роутинга для определения, показывать ли попап с деталями, или показывать страницу` не могу пока разобраться как использовать указанный пример для `createBrowserRouter` как-бы формально то у меня механизм роутинга для попапа используется но не так как в задании.

С `createBrowserRouter` скорее всего так не получится сделать. Нашел такой issue - https://github.com/remix-run/react-router/issues/9406, там нет однозначного ответа

2023-05-11 09:13 UTC, merged